# Site settings

title: Alex Ngo
tagline: Diary from a software developer, from journeyman to master craftsman
author: Alex Ngo
description: >- # this means to ignore newlines until "baseurl:"
  A personal diary from a journeyman to master.
  Some notes and thoughts during my career.
url: "http://alngo.com"

theme: minima

minima:
  social_links:
    github:
      name: alngo
      label: alngo
    linkedin: 
      name: alex-ngo-b7853a164
      label: Alex Ngo 

include:
  - _pages
  - _layouts

header_pages:
  - _pages/about.md
  - _pages/note.md

plugins:
  - jekyll-feed
  - jemoji
