title: Alngo
subtitle: A software engineering journey~
description: >- # this means to ignore newlines until "baseurl:"
  My focus has evolved from being an excellent individual contributor to becoming an effective team player. 
  Now, I primarily focus on communication and leadership skills.
signature: Cheers~!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

media:
  github: alngo
  linkedin: alex-ngo-b7853a164

sass:
  style: compressed

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"
