title: Alngo
subtitle: Engineering journey~
description: >- # this means to ignore newlines until "baseurl:"
  Thanks for reading!
signature: Cheers~!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.alngo.com" # the base hostname & protocol for your site, e.g. http://example.com

media:
  github: alngo
  linkedin: alex-ngo-b7853a164

sass:
  style: compressed

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"
